name: BabyGuarddd
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '^3.4.2'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  args: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0

flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
      - assets/loadscreen.png
      - assets/mainbg.png
      - assets/thermostat_hot.png
      - assets/thermostat_cold.png
      - assets/water_high.png
      - assets/water_low.png
      - assets/audio_on.png
      - assets/audio_off.png
      - assets/motion.png
